#! /bin/sh
#sudo  -u pi
export PYTHONPATH=/home/pi/.local/lib/python2.7/site-packages
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
sudo -u pi -H sh -c "python3 /home/pi/git/speedtest/src/test_speed1_3.py -t 10 -d /home/pi/git/speedtest/src/LCWA_d.txt -s 18002 &"
